name: Build Debug APK

on:
  push:
    branches:
      - main   # hoặc 'master' nếu repo của bạn dùng nhánh master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload built APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
